project:
  type: book
  post-render: 
    # - quarto render --profile slides
    - quarto render slides/
    - quarto render thesis/
    - quarto render manuscript/

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - .custom.scss
    toc-depth: 2
    notebook-links: true
    number-sections: false

comments:
  hypothesis: true

book:
  repo-url: "https://github.com/munch-group/xwas"
  repo-actions: [edit, issue, source]  
  title: "XWAS on ASD"
  author: "Shannon D'Urso"  
  chapters:
    - index.qmd
    - part: "Workflows"
      chapters: 
      - workflow.py
    - part: "Notebooks"
      chapters: 
      - notebooks/example.ipynb
    - part: "Reports"
      chapters: 
      - reports/example.qmd
    # - part: "Tables"
    #   chapters: 
    #   - tables/example.ipynb
    - part: "Slides"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/index.qmd 
    - part: "Thesis"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - thesis/index.qmd 
  downloads: [pdf]
     
bibliography: references.bib

